### PR TITLE
chore(deps): bump minor versions

### PR DESCRIPTION
**Pull request by skyfrk**
- chore(deps): bump docusaurus-plugin-openapi-docs from 1.2.2 to 1.4.1
- chore(deps): bump docusaurus-theme-openapi-docs from 1.2.2 to 1.4.1
- chore(deps): bump @docusaurus/core from 2.1.0 to 2.2.0
- chore(deps): bump @docusaurus/preset-classic from 2.1.0 to 2.2.0
- chore(deps): bump @svgr/webpack from 6.5.0 to 6.5.1
- chore(deps): bump @easyops-cn/docusaurus-search-local from 0.33.4 to 0.33.5

### CODE REVIEW

**Comment by skyfrk** [comment]
Search is broken :O

**Comment by skyfrk** [comment]
Search is still broken :(

**Comment by skyfrk** [comment]
Search is still broken...

**Comment by skyfrk** [comment]
Search works again!

**Review by DirtyNative — APPROVED** [review]

**Pull request merged**
