### PR TITLE
chore: regenerate GDS API docs to add `subscriptionType`

### PR DESCRIPTION
**Pull request by skyfrk**

### CODE REVIEW

**Comment by mstroppel** [comment]
Can we list the values that `subscriptionType` can have?

**Review by mstroppel — CHANGES_REQUESTED** [review]
Can we list the values that `subscriptionType` can have?

**Comment by skyfrk** [comment]
I would say no, since the subscription type can be any string and consumers should only use it for display purposes.

**Comment by mstroppel** [comment]
> I would say no, since the subscription type can be any string and consumers should only use it for display purposes.

User Story:
> HOMAG wants to know in their apps whether the user is a real customer or not. For real customer they have to pay some fee for using a library from an external provider. 
For this they need to know the subscription type to gather the usage data.  

This doesn't sound to me, that they only display the type.

**Comment by mstroppel** [comment]
Discussed with Helmut -> OK so far in order to not "inspire" more users to use the type for more than displaying.

**Review by mstroppel — APPROVED** [review]

**Pull request merged**
